# Generated by Django 5.2.9 on 2025-12-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={
                    "unique": "An account with this email already exists. Please sign in."
                },
                max_length=254,
                unique=True,
            ),
        ),
    ]
