# Generated by Django 5.2.9 on 2025-12-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("teacher", "Teacher"),
                    ("manager", "Manager"),
                    ("admin", "Admin"),
                ],
                default="teacher",
                max_length=20,
            ),
        ),
    ]
