# Generated by Django 5.2.9 on 2026-01-12 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("culture_centers", "0005_delete_culturecentermembership"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DispatchRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "teaching_language",
                    models.CharField(max_length=50, verbose_name="강의 언어"),
                ),
                (
                    "course_title",
                    models.CharField(max_length=120, verbose_name="강좌명"),
                ),
                (
                    "class_days",
                    models.JSONField(
                        blank=True, default=list, verbose_name="강의 요일"
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(blank=True, null=True, verbose_name="시작 시간"),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="종료 시간"),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="시작일"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="종료일"),
                ),
                (
                    "applicant_name",
                    models.CharField(max_length=100, verbose_name="신청자 이름"),
                ),
                (
                    "applicant_phone",
                    models.CharField(max_length=50, verbose_name="연락처"),
                ),
                (
                    "applicant_email",
                    models.EmailField(max_length=254, verbose_name="이메일"),
                ),
                (
                    "expected_teacher_count",
                    models.PositiveIntegerField(default=1, verbose_name="필요 강사 수"),
                ),
                (
                    "students_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="수강생 수(예상)"
                    ),
                ),
                (
                    "extra_requirements",
                    models.TextField(
                        blank=True, null=True, verbose_name="추가 요청사항"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("IN_REVIEW", "In review"),
                            ("MATCHED", "Matched"),
                            ("CONFIRMED", "Confirmed"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="NEW",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "culture_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispatch_requests",
                        to="culture_centers.culturecenter",
                        verbose_name="문화센터 지점",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispatch_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="요청자(매니저)",
                    ),
                ),
            ],
            options={
                "verbose_name": "강사 파견 요청",
                "verbose_name_plural": "강사 파견 요청",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="dispatch_re_status_175bfb_idx"
                    ),
                    models.Index(
                        fields=["culture_center"], name="dispatch_re_culture_7072b0_idx"
                    ),
                    models.Index(
                        fields=["requester"], name="dispatch_re_request_2848be_idx"
                    ),
                ],
            },
        ),
    ]
