# Generated by Django 5.2.9 on 2026-01-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispatch_requests", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dispatchrequest",
            name="expected_teacher_count",
        ),
        migrations.AddField(
            model_name="dispatchrequest",
            name="lecture_count",
            field=models.PositiveIntegerField(default=1, verbose_name="강의 횟수"),
        ),
    ]
