# Generated by Django 5.2.9 on 2026-01-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dispatch_requests",
            "0002_remove_dispatchrequest_expected_teacher_count_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="dispatchrequest",
            name="instructor_type",
            field=models.CharField(
                choices=[
                    ("KOREAN", "Korean"),
                    ("FOREIGN", "Foreigner"),
                    ("ANY", "Any"),
                ],
                default="ANY",
                max_length=10,
                verbose_name="강사 형태",
            ),
        ),
    ]
