# Generated by Django 5.2.9 on 2026-01-19 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispatch_requests", "0003_dispatchrequest_instructor_type"),
        ("teacher_applications", "0007_teacherapplication_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispatchrequest",
            name="teacher_name",
            field=models.ForeignKey(
                blank=True,
                help_text="TeacherApplication 중 status=ACCEPTED(채용 확정)인 강사만 선택 가능",
                limit_choices_to={"status": "ACCEPTED"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dispatch_requests",
                to="teacher_applications.teacherapplication",
                verbose_name="등록 강사",
            ),
        ),
        migrations.AlterField(
            model_name="dispatchrequest",
            name="instructor_type",
            field=models.CharField(
                choices=[
                    ("KOREAN", "한국인 강사"),
                    ("FOREIGN", "외국인 강사"),
                    ("ANY", "Any"),
                ],
                default="ANY",
                max_length=10,
                verbose_name="강사 형태",
            ),
        ),
    ]
