# Generated by Django 5.2.9 on 2026-01-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispatch_requests", "0004_dispatchrequest_teacher_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispatchrequest",
            name="start_date",
            field=models.DateField(verbose_name="시작일"),
        ),
    ]
