# Generated by Django 5.2.9 on 2026-02-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispatch_requests", "0005_alter_dispatchrequest_start_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dispatchrequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "강사 파견 요청 현황",
                "verbose_name_plural": "강사 파견 요청 현황",
            },
        ),
        migrations.AlterField(
            model_name="dispatchrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("IN_REVIEW", "In review"),
                    ("MATCHED", "Matched"),
                    ("PUBLISHED", "Published"),
                    ("CLOSED", "Closed"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="NEW",
                max_length=20,
                verbose_name="상태",
            ),
        ),
    ]
