# Generated by Django 5.2.9 on 2026-04-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispatch_requests", "0006_alter_dispatchrequest_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispatchrequest",
            name="application_deadline",
            field=models.DateTimeField(blank=True, null=True, verbose_name="지원 마감"),
        ),
        migrations.AddField(
            model_name="dispatchrequest",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="마감일"),
        ),
        migrations.AddField(
            model_name="dispatchrequest",
            name="notes_for_teachers",
            field=models.TextField(
                blank=True, default="", verbose_name="강사 안내 메모"
            ),
        ),
        migrations.AddField(
            model_name="dispatchrequest",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="게시일"),
        ),
        migrations.AlterField(
            model_name="dispatchrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "Requested"),
                    ("OPEN", "Open"),
                    ("CLOSED", "Closed"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="REQUESTED",
                max_length=20,
                verbose_name="상태",
            ),
        ),
    ]
