# Generated by Django 5.2.9 on 2026-01-20 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course_posts", "0001_initial"),
        ("culture_centers", "0005_delete_culturecentermembership"),
        ("teacher_applications", "0007_teacherapplication_latitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "teaching_language",
                    models.CharField(max_length=50, verbose_name="강의 언어"),
                ),
                (
                    "course_title",
                    models.CharField(max_length=120, verbose_name="강좌명"),
                ),
                (
                    "instructor_type",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="강사 형태"
                    ),
                ),
                (
                    "class_days",
                    models.JSONField(
                        blank=True, default=list, verbose_name="강의 요일"
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(blank=True, null=True, verbose_name="시작 시간"),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="종료 시간"),
                ),
                ("start_date", models.DateField(verbose_name="시작일")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="종료일"),
                ),
                (
                    "lecture_count",
                    models.PositiveIntegerField(default=1, verbose_name="강의 횟수"),
                ),
                (
                    "students_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="수강생 수(예상)"
                    ),
                ),
                (
                    "applicant_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="신청자 이름",
                    ),
                ),
                (
                    "applicant_phone",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="연락처"
                    ),
                ),
                (
                    "applicant_email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="이메일"
                    ),
                ),
                (
                    "extra_requirements",
                    models.TextField(
                        blank=True, null=True, verbose_name="추가 요청사항"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="비고"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("REVIEWING", "Reviewing"),
                            ("CONFIRMED", "Confirmed"),
                            ("ONGOING", "Ongoing"),
                            ("ENDED", "Ended"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="NEW",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "culture_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="courses",
                        to="culture_centers.culturecenter",
                        verbose_name="문화센터 지점",
                    ),
                ),
                (
                    "source_post",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="course",
                        to="course_posts.coursepost",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_courses",
                        to="teacher_applications.teacherapplication",
                        verbose_name="배정 강사",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="courses_cou_status_158bbf_idx"
                    ),
                    models.Index(
                        fields=["culture_center"], name="courses_cou_culture_1a0174_idx"
                    ),
                    models.Index(
                        fields=["start_date"], name="courses_cou_start_d_2c5b9f_idx"
                    ),
                ],
            },
        ),
    ]
