# Generated by Django 5.2.9 on 2026-02-15 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_posts", "0001_initial"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="source_post",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course",
                to="course_posts.coursepost",
            ),
        ),
    ]
