# Generated by Django 5.2.9 on 2026-04-20 21:32

import django.db.models.deletion
from django.db import migrations, models


def purge_legacy_rows(apps, schema_editor):
    """
    CoursePost → DispatchRequest 통합 리팩토링 전 잔여 테스트 데이터 제거.
    NOT NULL FK 전환(source_dispatch_request, CourseApplication.dispatch_request) 실패 방지용.
    """
    apps.get_model("courses", "Course").objects.all().delete()
    apps.get_model("course_posts", "CourseApplication").objects.all().delete()
    apps.get_model("course_posts", "CoursePost").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_course_source_post"),
        ("dispatch_requests", "0007_dispatchrequest_application_deadline_and_more"),
    ]

    operations = [
        migrations.RunPython(purge_legacy_rows, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="course",
            name="source_post",
        ),
        migrations.AddField(
            model_name="course",
            name="source_dispatch_request",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course",
                to="dispatch_requests.dispatchrequest",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[
                    ("CONFIRMED", "Confirmed"),
                    ("ONGOING", "Ongoing"),
                    ("ENDED", "Ended"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="CONFIRMED",
                max_length=20,
                verbose_name="상태",
            ),
        ),
    ]
