# Generated by Django 5.2.9 on 2026-01-20 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dispatch_requests", "0004_dispatchrequest_teacher_name_and_more"),
        ("teacher_applications", "0007_teacherapplication_latitude_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoursePost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("application_deadline", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("notes_for_teachers", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_course_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dispatch_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_post",
                        to="dispatch_requests.dispatchrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course post",
                "verbose_name_plural": "Course posts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("APPLIED", "Applied"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("REJECTED", "Rejected"),
                            ("SHORTLISTED", "Shortlisted"),
                            ("SELECTED", "Selected"),
                        ],
                        db_index=True,
                        default="APPLIED",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_applications",
                        to="teacher_applications.teacherapplication",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="course_posts.coursepost",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course application",
                "verbose_name_plural": "Course applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="coursepost",
            index=models.Index(fields=["status"], name="course_post_status_362820_idx"),
        ),
        migrations.AddIndex(
            model_name="coursepost",
            index=models.Index(
                fields=["published_at"], name="course_post_publish_8b21ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="courseapplication",
            index=models.Index(fields=["post"], name="course_post_post_id_acb573_idx"),
        ),
        migrations.AddIndex(
            model_name="courseapplication",
            index=models.Index(
                fields=["teacher"], name="course_post_teacher_3f39c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="courseapplication",
            index=models.Index(fields=["status"], name="course_post_status_fe2157_idx"),
        ),
        migrations.AddConstraint(
            model_name="courseapplication",
            constraint=models.UniqueConstraint(
                fields=("post", "teacher"), name="uniq_course_application_post_teacher"
            ),
        ),
    ]
