# Generated by Django 5.2.9 on 2026-04-20 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_posts", "0001_initial"),
        ("courses", "0003_remove_course_source_post_and_more"),
        ("dispatch_requests", "0007_dispatchrequest_application_deadline_and_more"),
        ("teacher_applications", "0007_teacherapplication_latitude_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursepost",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="coursepost",
            name="dispatch_request",
        ),
        migrations.RemoveConstraint(
            model_name="courseapplication",
            name="uniq_course_application_post_teacher",
        ),
        migrations.RemoveIndex(
            model_name="courseapplication",
            name="course_post_post_id_acb573_idx",
        ),
        migrations.RemoveField(
            model_name="courseapplication",
            name="post",
        ),
        migrations.AddField(
            model_name="courseapplication",
            name="dispatch_request",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="dispatch_requests.dispatchrequest",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="courseapplication",
            index=models.Index(
                fields=["dispatch_request"], name="course_post_dispatc_a2ae87_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="courseapplication",
            constraint=models.UniqueConstraint(
                fields=("dispatch_request", "teacher"),
                name="uniq_course_application_dispatch_teacher",
            ),
        ),
        migrations.DeleteModel(
            name="CoursePost",
        ),
    ]
