# Generated by Django 5.2.9 on 2025-12-14 02:12

import django.core.validators
import django.db.models.deletion
import teacher_applications.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        upload_to="teacher_applications/profile_images/",
                        validators=[
                            teacher_applications.models.validate_image_size_under_2mb,
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png"]
                            ),
                        ],
                        verbose_name="Profile image (2MB max, JPG/PNG) / 프로필 이미지 (최대 2MB, JPG/PNG)",
                    ),
                ),
                (
                    "profile_image_thumbnail",
                    models.ImageField(
                        blank=True,
                        editable=False,
                        null=True,
                        upload_to="teacher_applications/profile_images/thumbnails/",
                        verbose_name="Profile image thumbnail / 프로필 썸네일",
                    ),
                ),
                (
                    "profile_image_width",
                    models.PositiveIntegerField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Profile image width",
                    ),
                ),
                (
                    "profile_image_height",
                    models.PositiveIntegerField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Profile image height",
                    ),
                ),
                (
                    "profile_image_format",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=10,
                        verbose_name="Profile image format",
                    ),
                ),
                (
                    "profile_image_filesize",
                    models.PositiveIntegerField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Profile image file size (bytes)",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="First name / 이름"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="Last name / 성"),
                ),
                (
                    "korean_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Korean name / 한국 이름 (선택)",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MALE", "Male / 남성"),
                            ("FEMALE", "Female / 여성"),
                            ("OTHER", "Other / 기타"),
                            ("PREFER_NOT", "Prefer not to say / 선택하지 않음"),
                        ],
                        max_length=20,
                        verbose_name="Gender / 성별",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of birth / 생년월일"
                    ),
                ),
                (
                    "nationality",
                    models.CharField(max_length=100, verbose_name="Nationality"),
                ),
                (
                    "native_language",
                    models.CharField(
                        max_length=100, verbose_name="Native language / 모국어"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email address"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=30, verbose_name="Phone number"),
                ),
                (
                    "address_line1",
                    models.CharField(
                        max_length=255,
                        verbose_name="Address (street & detail) / 주소 (도로명·상세)",
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="City / 도시")),
                (
                    "district",
                    models.CharField(max_length=100, verbose_name="District / 구·군"),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Postal code / 우편번호"
                    ),
                ),
                (
                    "visa_type",
                    models.CharField(
                        choices=[
                            ("E-2", "E-2"),
                            ("F-2", "F-2"),
                            ("F-4", "F-4"),
                            ("F-5", "F-5"),
                            ("D-10", "D-10"),
                            ("OTHER", "Other / 기타"),
                        ],
                        max_length=20,
                        verbose_name="Visa type",
                    ),
                ),
                (
                    "visa_expiry_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Visa expiry date / 비자 만료일",
                    ),
                ),
                (
                    "visa_scan",
                    models.ImageField(
                        upload_to="teacher_applications/visa_scans/",
                        validators=[
                            teacher_applications.models.validate_image_size_under_2mb,
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png"]
                            ),
                        ],
                        verbose_name="Visa copy (2MB max, JPG/PNG) / 비자 사본 (최대 2MB, JPG/PNG)",
                    ),
                ),
                (
                    "teaching_languages",
                    models.CharField(
                        choices=[
                            ("English", "English"),
                            ("Japanese", "Japanese"),
                            ("Chinese", "Chinese"),
                            ("Spanish", "Spanish"),
                        ],
                        help_text="Please select one language. / 한 가지만 선택해 주세요.",
                        max_length=20,
                        verbose_name="Languages you can teach / 가르칠 수 있는 언어",
                    ),
                ),
                (
                    "preferred_subjects",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Conversation, Business English, Kids / 예: 회화, 비즈니스, 어린이 영어 등",
                        max_length=255,
                        verbose_name="Preferred subjects / 선호 수업 분야",
                    ),
                ),
                (
                    "total_teaching_experience_years",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Total teaching experience (years) / 총 강의 경력 (년)",
                    ),
                ),
                (
                    "korea_teaching_experience_years",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Teaching experience in Korea (years) / 한국 강의 경력 (년)",
                    ),
                ),
                (
                    "self_introduction",
                    models.TextField(
                        help_text="Briefly introduce yourself as a teacher. / 강사로서 본인을 간단히 소개해 주세요.",
                        verbose_name="Self introduction / 자기소개",
                    ),
                ),
                (
                    "education_history",
                    models.TextField(
                        help_text="List universities, degrees, majors, and years. / 학교, 학위, 전공, 기간 등을 적어 주세요.",
                        verbose_name="Education history / 학력 사항",
                    ),
                ),
                (
                    "experience_history",
                    models.TextField(
                        help_text="List teaching and work experience in order. / 강의 및 근무 경력을 순서대로 적어 주세요.",
                        verbose_name="Teaching & work experience / 강의 및 근무 경력",
                    ),
                ),
                (
                    "certifications",
                    models.TextField(
                        blank=True,
                        help_text="e.g. TESOL, CELTA, etc. / 예: TESOL, CELTA 등",
                        verbose_name="Certificates & qualifications / 자격증 및 인증",
                    ),
                ),
                (
                    "teaching_style",
                    models.TextField(
                        blank=True,
                        verbose_name="Teaching style & strengths / 수업 스타일 및 강점",
                    ),
                ),
                (
                    "additional_info",
                    models.TextField(
                        blank=True,
                        verbose_name="Additional information / 기타 참고 사항",
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FULL_TIME", "Full-time / 풀타임"),
                            ("PART_TIME", "Part-time / 파트타임"),
                            ("FREELANCE", "Freelance / 프리랜서"),
                            ("ANY", "Any / 상관없음"),
                        ],
                        max_length=20,
                        verbose_name="Employment type / 근무 형태",
                    ),
                ),
                (
                    "preferred_locations",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Seoul, Online only / 예: 서울, 온라인만 등",
                        max_length=255,
                        verbose_name="Preferred locations / 선호 근무 지역",
                    ),
                ),
                (
                    "available_time_slots",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Weekdays evenings, Weekends / 예: 평일 저녁, 주말 등",
                        max_length=255,
                        verbose_name="Available time slots / 근무 가능 시간대",
                    ),
                ),
                (
                    "available_from_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Available from / 근무 시작 가능 일자",
                    ),
                ),
                (
                    "consent_personal_data",
                    models.BooleanField(
                        default=False,
                        verbose_name="Consent to personal data usage / 개인정보 수집·이용 동의",
                    ),
                ),
                (
                    "consent_data_retention",
                    models.BooleanField(
                        default=False,
                        verbose_name="Consent to data retention / 정보 보관 기간 동의",
                    ),
                ),
                (
                    "consent_third_party_sharing",
                    models.BooleanField(
                        default=False,
                        verbose_name="Consent to share with partner institutes / 제3자 제공 동의",
                    ),
                ),
                (
                    "confirmation_info_true",
                    models.BooleanField(
                        default=False,
                        verbose_name="Confirm information is true / 정보의 정확성 확인",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New / 신규"),
                            ("IN_REVIEW", "In review / 검토 중"),
                            ("ACCEPTED", "Accepted / 채용 확정"),
                            ("REJECTED", "Rejected / 불합격"),
                        ],
                        default="NEW",
                        max_length=20,
                        verbose_name="지원 상태",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="신청 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 일시"),
                ),
                (
                    "memo",
                    models.TextField(
                        blank=True,
                        help_text="특이 사항 등 간단한 메모 (관리자 전용) / Brief notes for special remarks (Admin only)",
                        verbose_name="Memo / 메모",
                    ),
                ),
                (
                    "evaluation_result",
                    models.TextField(
                        blank=True,
                        help_text="전체적인 이력서 평가 결과 (1000자 이내, 관리자 전용) / Overall resume evaluation result (max 1000 chars, Admin only)",
                        max_length=1000,
                        verbose_name="Evaluation Result / 평가 결과",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_application",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User / 사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher application",
                "verbose_name_plural": "Teacher applications",
                "ordering": ["-created_at"],
            },
        ),
    ]
