# Generated by Django 5.2.9 on 2025-12-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher_applications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacherapplication",
            name="teaching_languages",
            field=models.CharField(
                choices=[
                    ("ENGLISH", "English"),
                    ("JAPANESE", "Japanese"),
                    ("CHINESE", "Chinese"),
                    ("SPANISH", "Spanish"),
                ],
                help_text="Please select one language. / 한 가지만 선택해 주세요.",
                max_length=20,
                verbose_name="Languages you can teach / 가르칠 수 있는 언어",
            ),
        ),
    ]
