# Generated by Django 5.2.9 on 2025-12-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher_applications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherapplication",
            name="profile_image_filesize",
            field=models.PositiveIntegerField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="Profile image file size (bytes)",
            ),
        ),
        migrations.AddField(
            model_name="teacherapplication",
            name="profile_image_format",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=10,
                verbose_name="Profile image format",
            ),
        ),
        migrations.AddField(
            model_name="teacherapplication",
            name="profile_image_height",
            field=models.PositiveIntegerField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="Profile image height",
            ),
        ),
        migrations.AddField(
            model_name="teacherapplication",
            name="profile_image_thumbnail",
            field=models.ImageField(
                blank=True,
                editable=False,
                null=True,
                upload_to="teacher_applications/profile_images/thumbnails/",
                verbose_name="Profile image thumbnail / 프로필 썸네일",
            ),
        ),
        migrations.AddField(
            model_name="teacherapplication",
            name="profile_image_width",
            field=models.PositiveIntegerField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="Profile image width",
            ),
        ),
    ]
