# Generated by Django 5.2.9 on 2025-12-18 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher_applications", "0002_alter_teacherapplication_evaluation_result"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacherapplication",
            name="visa_type",
            field=models.CharField(
                choices=[
                    ("F-2", "F-2"),
                    ("F-4", "F-4"),
                    ("F-5", "F-5"),
                    ("F-6", "F-6"),
                    ("OTHER", "Other / 기타"),
                ],
                max_length=20,
                verbose_name="Visa type",
            ),
        ),
    ]
