# Generated by Django 5.2.9 on 2025-12-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher_applications", "0003_alter_teacherapplication_visa_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacherapplication",
            name="nationality",
            field=models.CharField(
                choices=[
                    ("USA", "United States / 미국"),
                    ("UK", "United Kingdom / 영국"),
                    ("CANADA", "Canada / 캐나다"),
                    ("IRELAND", "Ireland / 아일랜드"),
                    ("AUSTRALIA", "Australia / 호주"),
                    ("NEW_ZEALAND", "New Zealand / 뉴질랜드"),
                    ("SOUTH_AFRICA", "South Africa / 남아프리카공화국"),
                    ("PHILIPPINES", "Philippines / 필리핀"),
                    ("SOUTH_KOREA", "South Korea / 대한민국"),
                    ("JAPAN", "Japan / 일본"),
                    ("CHINA", "China / 중국"),
                    ("OTHER", "Other / 기타"),
                ],
                max_length=100,
                verbose_name="Nationality",
            ),
        ),
        migrations.AlterField(
            model_name="teacherapplication",
            name="native_language",
            field=models.CharField(
                choices=[
                    ("ENGLISH", "English / 영어"),
                    ("KOREAN", "Korean / 한국어"),
                    ("JAPANESE", "Japanese / 일본어"),
                    ("CHINESE", "Chinese / 중국어"),
                    ("SPANISH", "Spanish / 스페인어"),
                    ("OTHER", "Other / 기타"),
                ],
                max_length=100,
                verbose_name="Native language / 모국어",
            ),
        ),
    ]
