# Generated by Django 5.2.9 on 2025-12-21 00:17

import django.core.validators
import teacher_applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher_applications", "0004_alter_teacherapplication_nationality_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherapplication",
            name="introduction_youtube_url",
            field=models.URLField(
                blank=True,
                help_text="e.g. https://youtu.be/kkkUVYjxN1U?si=... / 예: 유튜브 소개 영상 링크",
                max_length=500,
                null=True,
                validators=[
                    django.core.validators.URLValidator(),
                    teacher_applications.models.validate_youtube_url,
                ],
                verbose_name="YouTube intro video link / 유튜브 소개 영상 링크 (선택)",
            ),
        ),
    ]
