# Generated by Django 5.2.9 on 2025-12-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher_applications", "0005_teacherapplication_introduction_youtube_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacherapplication",
            name="available_time_slots",
            field=models.JSONField(
                blank=True,
                help_text="Weekly timetable selection stored as JSON / 주간 타임테이블 선택값(JSON)으로 저장",
                null=True,
                verbose_name="Available time slots / 근무 가능 시간대",
            ),
        ),
    ]
