# Generated by Django 5.2.9 on 2026-01-06 01:11

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher_applications", "0006_alter_teacherapplication_available_time_slots"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherapplication",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=6,
                help_text="e.g. 37.313313 (WGS84). Optional for now. / 예: 37.313313 (선택)",
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90),
                ],
                verbose_name="Latitude / 위도",
            ),
        ),
        migrations.AddField(
            model_name="teacherapplication",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=6,
                help_text="e.g. 127.081270 (WGS84). Optional for now. / 예: 127.081270 (선택)",
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ],
                verbose_name="Longitude / 경도",
            ),
        ),
        migrations.AddIndex(
            model_name="teacherapplication",
            index=models.Index(fields=["latitude", "longitude"], name="ta_lat_lng_idx"),
        ),
    ]
