# Generated by Django 5.2.9 on 2026-01-08 00:24

import dispatches.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("culture_centers", "0004_culturecentermembership"),
        ("teacher_applications", "0007_teacherapplication_latitude_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DispatchApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="지원 메시지")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("APPLIED", "Applied / 지원"),
                            ("WITHDRAWN", "Withdrawn / 지원취소"),
                            ("REJECTED", "Rejected / 탈락"),
                            ("SHORTLISTED", "Shortlisted / 후보"),
                            ("SELECTED", "Selected / 선정"),
                        ],
                        db_index=True,
                        default="APPLIED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "teacher_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispatch_applications",
                        to="teacher_applications.teacherapplication",
                        verbose_name="강사(이력서)",
                    ),
                ),
            ],
            options={
                "verbose_name": "강사 지원",
                "verbose_name_plural": "강사 지원",
            },
        ),
        migrations.CreateModel(
            name="DispatchRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "teaching_language",
                    models.CharField(
                        choices=[
                            ("English", "English"),
                            ("Japanese", "Japanese"),
                            ("Chinese", "Chinese"),
                            ("Spanish", "Spanish"),
                        ],
                        max_length=20,
                        verbose_name="강의 언어",
                    ),
                ),
                (
                    "course_title",
                    models.CharField(max_length=200, verbose_name="강좌명"),
                ),
                (
                    "weekdays",
                    models.JSONField(
                        help_text="e.g. ['MON','WED']",
                        validators=[dispatches.models.validate_weekdays],
                        verbose_name="강의 요일(복수)",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="수업 시작 시간")),
                ("end_time", models.TimeField(verbose_name="수업 종료 시간")),
                ("start_date", models.DateField(verbose_name="강의 시작일")),
                ("end_date", models.DateField(verbose_name="강의 종료일")),
                (
                    "target",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="대상(성인/키즈 등)"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="레벨(초급/중급 등)"
                    ),
                ),
                (
                    "headcount",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="예상 인원"
                    ),
                ),
                (
                    "is_online",
                    models.BooleanField(default=False, verbose_name="온라인 여부"),
                ),
                (
                    "requirements",
                    models.TextField(blank=True, verbose_name="요청/필요 조건"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "requester_name",
                    models.CharField(max_length=100, verbose_name="신청자 이름"),
                ),
                (
                    "requester_phone",
                    models.CharField(max_length=50, verbose_name="연락처"),
                ),
                (
                    "requester_email",
                    models.EmailField(max_length=254, verbose_name="이메일"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested / 요청됨"),
                            ("REVIEWING", "Reviewing / 검토 중"),
                            ("PUBLISHED", "Published / 공고 중"),
                            ("CLOSED", "Closed / 모집 마감"),
                            ("ASSIGNED", "Assigned / 강사 배치"),
                            ("CONFIRMED", "Confirmed / 파견 확정"),
                            ("CANCELED", "Canceled / 취소"),
                        ],
                        db_index=True,
                        default="REQUESTED",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="공고 시각"
                    ),
                ),
                (
                    "application_deadline",
                    models.DateField(blank=True, null=True, verbose_name="지원 마감일"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "culture_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispatch_requests",
                        to="culture_centers.culturecenter",
                        verbose_name="문화센터 지점",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispatch_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="요청자(User)",
                    ),
                ),
            ],
            options={
                "verbose_name": "강사 파견 요청/공고",
                "verbose_name_plural": "강사 파견 요청/공고",
            },
        ),
        migrations.CreateModel(
            name="DispatchAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ASSIGNED", "Assigned / 배치됨"),
                            (
                                "CONFIRMED_BY_TEACHER",
                                "Confirmed by teacher / 강사 확인",
                            ),
                            ("CONFIRMED_BY_CENTER", "Confirmed by center / 센터 확인"),
                            ("CONFIRMED", "Confirmed / 최종 확정"),
                            ("CANCELED", "Canceled / 취소"),
                        ],
                        db_index=True,
                        default="ASSIGNED",
                        max_length=30,
                    ),
                ),
                (
                    "admin_memo",
                    models.TextField(blank=True, verbose_name="관리자 메모"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "selected_application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignment",
                        to="dispatches.dispatchapplication",
                        verbose_name="선정된 지원",
                    ),
                ),
                (
                    "dispatch_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment",
                        to="dispatches.dispatchrequest",
                        verbose_name="파견 요청",
                    ),
                ),
            ],
            options={
                "verbose_name": "강사 배치/파견",
                "verbose_name_plural": "강사 배치/파견",
            },
        ),
        migrations.AddField(
            model_name="dispatchapplication",
            name="dispatch_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="dispatches.dispatchrequest",
                verbose_name="파견 요청",
            ),
        ),
        migrations.AddIndex(
            model_name="dispatchrequest",
            index=models.Index(
                fields=["culture_center", "status"],
                name="dispatches__culture_514876_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dispatchrequest",
            index=models.Index(
                fields=["teaching_language", "status"],
                name="dispatches__teachin_df2899_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dispatchapplication",
            index=models.Index(
                fields=["dispatch_request", "status"],
                name="dispatches__dispatc_8b0242_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dispatchapplication",
            index=models.Index(
                fields=["teacher_application", "status"],
                name="dispatches__teacher_57c9df_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="dispatchapplication",
            constraint=models.UniqueConstraint(
                fields=("dispatch_request", "teacher_application"),
                name="uniq_dispatch_request_teacher_application",
            ),
        ),
    ]
