# Generated by Django 5.2.9 on 2025-12-28 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="지역"),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="비고"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "지역",
                "verbose_name_plural": "지역",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CultureCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "center_name",
                    models.CharField(max_length=100, verbose_name="문화센터 이름"),
                ),
                (
                    "branch_name",
                    models.CharField(max_length=100, verbose_name="지점 이름"),
                ),
                (
                    "address_detail",
                    models.CharField(max_length=255, verbose_name="상세 주소"),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="비고"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="culture_centers",
                        to="culture_centers.region",
                        verbose_name="지역",
                    ),
                ),
            ],
            options={
                "verbose_name": "문화센터",
                "verbose_name_plural": "문화센터",
                "indexes": [
                    models.Index(
                        fields=["center_name"], name="culture_cen_center__bcbd84_idx"
                    ),
                    models.Index(
                        fields=["branch_name"], name="culture_cen_branch__059ad6_idx"
                    ),
                    models.Index(
                        fields=["region"], name="culture_cen_region__60ec54_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("center_name", "region", "branch_name"),
                        name="uniq_center_region_branch",
                    )
                ],
            },
        ),
    ]
