# Generated by Django 5.2.9 on 2025-12-29 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("culture_centers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="culturecenter",
            name="center_phone",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="센터 전화번호"
            ),
        ),
        migrations.AddField(
            model_name="culturecenter",
            name="manager_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="담당자 이메일"
            ),
        ),
        migrations.AddField(
            model_name="culturecenter",
            name="manager_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="담당자 이름"
            ),
        ),
        migrations.AddField(
            model_name="culturecenter",
            name="manager_phone",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="담당자 전화번호"
            ),
        ),
        migrations.AlterField(
            model_name="culturecenter",
            name="center",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="branches",
                to="culture_centers.center",
                verbose_name="문화센터 이름",
            ),
        ),
    ]
