# Generated by Django 5.2.9 on 2026-01-06 01:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("culture_centers", "0002_culturecenter_center_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="culturecenter",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=6,
                help_text="e.g. 37.313313 (WGS84). Optional for now.",
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90),
                ],
                verbose_name="위도",
            ),
        ),
        migrations.AddField(
            model_name="culturecenter",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=6,
                help_text="e.g. 127.081270 (WGS84). Optional for now.",
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ],
                verbose_name="경도",
            ),
        ),
        migrations.AddIndex(
            model_name="culturecenter",
            index=models.Index(fields=["latitude", "longitude"], name="cc_lat_lng_idx"),
        ),
    ]
