# Generated by Django 5.2.9 on 2026-01-08 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "culture_centers",
            "0003_culturecenter_latitude_culturecenter_longitude_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CultureCenterMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("MANAGER", "Manager / 매니저"),
                            ("STAFF", "Staff / 스태프"),
                        ],
                        default="MANAGER",
                        max_length=20,
                        verbose_name="역할",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "culture_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="culture_centers.culturecenter",
                        verbose_name="문화센터 지점",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="culture_center_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "문화센터 지점 멤버십",
                "verbose_name_plural": "문화센터 지점 멤버십",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "culture_center"),
                        name="uniq_user_culture_center_membership",
                    )
                ],
            },
        ),
    ]
