# Generated by Django 5.2.9 on 2026-01-08 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("culture_centers", "0004_culturecentermembership"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CultureCenterMembership",
        ),
    ]
